repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
                flake8-bugbear==21.4.3,
                flake8-django==1.1.2,
                flake8-docstrings==1.6.0,
                flake8-eradicate==1.0.0,
                flake8-quotes==3.2.0,
                pep8-naming==0.11.1,
        ]
        args: [
                --max-line-length=100,
                --inline-quotes=double,
                --docstring-convention=numpy,
                "--ignore=D100,D104",
        ]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py38-plus]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
    -   id: yesqa

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
