repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/wemake-services/dotenv-linter
    rev: 0.2.0
    hooks:
    -   id: dotenv-linter

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: Python style guide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
